/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.praktikum02072026;

import javax.swing.JOptionPane;

/**
 *
 * @author Agung
 */
public class FormPemesananKafe extends javax.swing.JPanel {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormPemesananKafe.class.getName());

    static void setTotalMinuman(String total) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    static void setTotalMakanan(String total) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    private String nilai;
    /**
     * Creates new form FormPemesananKafe
     */
    public FormPemesananKafe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtMeja = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMakanan = new javax.swing.JTextField();
        txtMinuman = new javax.swing.JTextField();
        btnMenuMakanan = new javax.swing.JButton();
        btnMenuMinuman = new javax.swing.JButton();
        btnTotal = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        txtTotal = new javax.swing.JTextField();
        btnSelesai = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("FORM PEMESANAN KAFE ABC");

        jLabel2.setText("Nama Pelanggan");

        jLabel3.setText("Nomor Meja");

        txtNama.addActionListener(this::txtNamaActionPerformed);

        jLabel4.setText("Total Harga Makanan");

        jLabel5.setText("Total Harga Minuman");

        txtMakanan.setText("0");
        txtMakanan.addActionListener(this::txtMakananActionPerformed);

        txtMinuman.setText("0");
        txtMinuman.addActionListener(this::txtMinumanActionPerformed);

        btnMenuMakanan.setText("MENU MAKANAN");
        btnMenuMakanan.addActionListener(this::btnMenuMakananActionPerformed);

        btnMenuMinuman.setText("MENU MINUMAN");
        btnMenuMinuman.addActionListener(this::btnMenuMinumanActionPerformed);

        btnTotal.setText("Hitung");
        btnTotal.addActionListener(this::btnTotalActionPerformed);

        jLabel6.setText("Total Harga");

        jButton4.setText("Reset");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jButton5.setText("Keluar");
        jButton5.addActionListener(this::jButton5ActionPerformed);

        txtTotal.setText("0");

        btnSelesai.setText("Selesai");
        btnSelesai.addActionListener(this::btnSelesaiActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtMeja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(btnTotal)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtMinuman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 2, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtMakanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(127, 127, 127)
                                        .addComponent(btnSelesai)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnMenuMinuman)
                            .addComponent(btnMenuMakanan)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jButton4)
                        .addGap(36, 36, 36)
                        .addComponent(jButton5)))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtMakanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMeja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtMinuman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMenuMakanan)
                    .addComponent(btnTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMenuMinuman)
                    .addComponent(jLabel6)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(btnSelesai))
                .addGap(35, 35, 35))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void txtMinumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMinumanActionPerformed
        txtMinuman.setText(nilai);
    }//GEN-LAST:event_txtMinumanActionPerformed

    private void btnMenuMinumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuMinumanActionPerformed
        MenuMinuman frm = new MenuMinuman(this);
        frm.setVisible(true);
    }//GEN-LAST:event_btnMenuMinumanActionPerformed

    private void btnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalActionPerformed
        if(txtNama.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Nama Masih Kosong", "Peringatan", JOptionPane.ERROR_MESSAGE);
        }
        else if(txtMeja.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Nomor Meja Masih Kosong", "Peringatan", JOptionPane.ERROR_MESSAGE);
        }
        else{
        double makanan = Double.parseDouble(txtMakanan.getText());
        double minuman = Double.parseDouble(txtMinuman.getText());
        double total = makanan + minuman;
        
        txtTotal.setText(Double.toString(total));
    }//GEN-LAST:event_btnTotalActionPerformed

    private void btnMenuMakananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuMakananActionPerformed
        MenuMakanan frm = new MenuMakanan(this);
        frm.setVisible(true);
    }//GEN-LAST:event_btnMenuMakananActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        txtNama.setText("");
        txtMeja.setText("");
        txtMakanan.setText("");
        txtMinuman.setText("");
        txtTotal.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int pil = JOptionPane.showConfirmDialog(this, "Apakah mau keluar","Konfirmasi Keluar", JOptionPane.YES_NO_OPTION);
      
        if(pil == JOptionPane.YES_OPTION)
            System.exit(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelesaiActionPerformed
        try{
        String nama = txtNama.getText();
        int meja = Integer.parseInt(txtMeja.getText());
        String total = txtTotal.getText();
        JOptionPane.showMessageDialog(this, "Nama : " + nama + "\nMeja : " + meja+"\nTotal Pesanan : Rp."+total, "Pesanan Sudah Dibuat", JOptionPane.INFORMATION_MESSAGE);
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Masukan Input Yang Benar");
        }
    }//GEN-LAST:event_btnSelesaiActionPerformed

    private void txtMakananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMakananActionPerformed
        txtMakanan.setText(nilai);
    }//GEN-LAST:event_txtMakananActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenuMakanan;
    private javax.swing.JButton btnMenuMinuman;
    private javax.swing.JButton btnSelesai;
    private javax.swing.JButton btnTotal;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtMakanan;
    private javax.swing.JTextField txtMeja;
    private javax.swing.JTextField txtMinuman;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
